#!/bin/python3

import math
import os
import random
import re
import sys

def insertionSort1(n, arr):
    num = arr[n-1]
    arr[n-1] = arr [n-2]
    for j in arr:
        print (j,end=" ")
    print ("")
    for i in range (n-2,-1,-1):
        if num < arr [i-1] and i!=0:
            arr [i] = arr [i-1]
            for j in arr:
                print (j,end=" ")
            print ("")
        elif i == 0 and arr[i-1] > num:
            arr[i] = num
            for j in arr:
                print (j,end=" ")
            print ("")
        elif num > arr[i-1]:
            arr [i] = num
            for j in arr:
                print (j,end=" ")
            print ("")
            break
   
if __name__ == '__main__':
    n = int(input().strip())

    arr = list(map(int, input().rstrip().split()))

    insertionSort1(n, arr)
